data_directory: SCRC/pipeline_data
fail_on_hash_mismatch: true

read:
  - where:
      data_product: human/age_var_symtomatic_rates
    use:
      version: 1.0.0
  - where:
      data_product: human/health_burden_processes
    use:
      version: 1.0.0
    