name: LSHTM Model

on: [ push ]

jobs:
  build:
    name : Ubuntu Linux R
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install Requirements
        run: |
             sudo apt-get install apt-transport-https software-properties-common r-cran-rcppgsl -y
      - name: Install R
        run: |
             sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
             sudo add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/'
             sudo apt-get update
             sudo apt-get install r-base
      - name: Install Required Libraries
        env: 
              DEBIAN_FRONTEND: noninteractive
        run: |
              install.packages("rlang")
              install.packages("stringr")
              install.packages("data.table")
              install.packages("ggplot2")
              install.packages("qs")
              install.packages("lubridate")
              install.packages("nloptr")
              install.packages("HDInterval")
              install.packages("cowplot")
              install.packages("testit")
              install.packages("readxl")
        shell: Rscript {0}
      - name: Run Model Locally in Dump Mode
        run: Rscript run_model.R 1 --local --dump
      - name: Test Outputs
        run: Rscript test/regression/test_params.R 
